resolutions = [512]

enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 9

num_repeats = 1  # whatever you want

[[directory]]
# The target images go in here. These are the images that the model will learn to produce.
path = '/home/anon/data/images/kontext/target'
# The control/context images go in here, with the same name as the corresponding target images.
# Every target image must have a corresponding control image or it will fail.
control_path = '/home/anon/data/images/kontext/control'

# You can train on normal t2i datasets at the same time. But they have to be in a different directory.

# [[directory]]
# path = '/home/anon/data/images/normal_t2i_dataset'